// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isPostgres = process.env["DATABASE_PROVIDER"] === "postgresql";

export default defineConfig({
  schema: isPostgres
    ? "prisma/schema.postgresql.prisma"
    : "prisma/schema.prisma",
  migrations: {
    path: isPostgres
      ? "prisma/migrations-postgresql"
      : "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
